"""initial migration

Revision ID: 05017bac9779
Revises: 
Create Date: 2026-07-10 14:25:16.793805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05017bac9779'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('obligations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('RUB', 'USD', 'EUR', name='currency_enum'), server_default=sa.text("'RUB'"), nullable=False),
    sa.Column('category', sa.Enum('SUBSCRIPTION', 'WARRANTY', 'BILL', 'INSURANCE', name='category_enum'), nullable=False),
    sa.Column('recurrence', sa.Enum('MONTHLY', 'QUARTERLY', 'YEARLY', name='recurrence_enum'), nullable=True),
    sa.Column('next_payment_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CANCELLED', 'EXPIRED', name='status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('obligation_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('RUB', 'USD', 'EUR', name='currency_enum'), server_default=sa.text("'RUB'"), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('obligations')
    # ### end Alembic commands ###
